            - name: Flutter Check

# uses: AcmeSoftwareLLC/flutter-build@aa7592b3d5b59c269674fc6789cab5658f88a104
  uses: AcmeSoftwareLLC/flutter-build@v1.0.1
  with:
    # Platform
    platform: 
    # Build Name
    build-name: # optional
    # Build Number
    build-number: # optional
    # Base Href
    base-href: # optional
    # Dart Define File
    dart-define-file: # optional
    # Working Directory
    working-directory: # optional, default is .
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
